apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-controller-webhook-service
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app.kubernetes.io/name: aws-load-balancer-controller