apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds
  - deployment

namespace: kube-system

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: aws-load-balancer-controller