apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: controller
        args:
        - --cluster-name=$(CLUSTER_NAME)
        - --ingress-class=alb
        - --metrics-bind-addr=:8080
        - --enable-pod-readiness-gate-inject=true
        - --enable-shield=true
        - --enable-waf=true
        - --enable-wafv2=true
        - --log-level=debug
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi